JoinTester.class: JoinTester.java Record.java RecordComparator.java Scheme.java SortMergeJoin.java Utils.java Join.java HashJoin.java
	javac *.java

run: JoinTester.class
	java JoinTester 10 100

clean:
	rm *.class
	rm hj*.txt smj*.txt
	rm sorted*.txt
